# Generated by Django 3.1.7 on 2021-02-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_created',
            new_name='date',
        ),
    ]
